
name: linux

on:
  push:
    paths: 
      - linux

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get install gcc-8
      - run: wget -q https://github.com/happygeon/linux/archive/$(git rev-parse @:./linux).zip -O linux.zip
      - run: unzip -q linux.zip

      - run: ./install-deps.sh
      
      - run: ./build-linux.sh linux-$(git rev-parse @:./linux) tinyconfig
